name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.12.3'

      - run: |
          mkdir ./cover
          mix local.hex --force
          mix local.rebar --force
          mix deps.clean --unused
          mix deps.get
          mix deps.compile
        name: Compile Dependencies

      - run: |
          MIX_ENV=test mix test --cover
        name: Run Tests

      - run: |
          MIX_ENV=performance mix escript.build
        name: Compile
