name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '24'
          elixir-version: '1.12.2'
      
      - run: |
          iex --version
          erl --version
          mix --version

      - run: |
          mkdir ./cover
          mix local.hex --force
          mix local.rebar --force
          mix deps.clean --unused
          mix deps.get
          mix deps.compile
        name: Compile Dependencies

      - run: |
          MIX_ENV=performance mix escript.build
        name: Compile
      
      - run: |
          MIX_ENV=test mix test --cover  
        name: Unit Tests
